name: reddit_pixel_example
description: Demonstrates how to use the reddit_pixel package.

publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  reddit_pixel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=8.0.0 <11.0.0"

flutter:
  uses-material-design: true
